name: Generate Snake SVG

on:
  schedule: # her 12 saatte bir çalışacak
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: output/snake.svg
          palette: github-dark # veya github-light

      - name: Commit & Push with PAT
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add output/snake.svg
          git commit -m "Update snake SVG" || echo "No changes to commit"
          git push https://emreucbudak:${{ secrets.PAT_TOKEN }}@github.com/emreucbudak/emreucbudak.git
